define([
   "skylark-slax-runtime",
   "skylark-bootstrap3/loadedInit",
   "skylark-domx-plugins-menus",
   "skylark-widgets-codeground",
   "skylark-widgets-textpad",
   "skylark-jqueryui",
   "skylark-domx-i18n",
   "skylark-jquery-timeago",
   "skylark-jquery-form",
   "skylark-jquery-textcomplete",
   "skylark-benchpress",
   "skylark-sortable",
   "skylark-slideout",
   "./wrappers/bootbox",
   "./groups/memberlist",
   "./misc/alerts",
   "./misc/autocomplete",
   "./misc/chat",
   "./misc/components",
   "./misc/coverPhoto",
   "./misc/flags",
//   "./misc/handleBack",
   "./misc/helpers",
   "./misc/iconSelect",
//   "./misc/navigator",
//   "./misc/notifications",
   './misc/infinitescroll',
   "./misc/pictureCropper",
   "./misc/scrollStop",
//   "./misc/search",
   "./misc/settings",
   "./misc/share",
   "./misc/sort",
   "./misc/sounds",
   "./misc/storage",
   "./misc/taskbar",
   "./misc/translator",
   "./misc/uploader",
   './topics/categorySearch',
   './topics/categorySelector',
   "./pagex/page",
   "./app",
   "./init"

],function(slax,bsInit){
//	bsInit();
	return slax;
})

